version: '3.9'
services:
  database_x:
    image: postgres:latest
    container_name: database_x
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - ./sql/table.sql:/docker-entrypoint-initdb.d/init_0.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/init_1.sql


  database_y:
    image: postgres:latest
    container_name: database_y
    restart: always
    env_file:
      - database.env
    ports:
      - "5433:5432"
    volumes:
      - ./sql/table.sql:/docker-entrypoint-initdb.d/init_0.sql
