version: '3.9'
services:
  database:
    image: postgres:latest
    container_name: database_x
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init_scripts.sql:/docker-entrypoint-initdb.d/0_init.sql